-- RAW
SELECT * FROM CLAIMS_DEMO.RAW.CLAIMS_RAW ORDER BY _ingested_at DESC;

-- CURATED
SELECT * FROM CLAIMS_DEMO.CURATED.FACT_CLAIMS ORDER BY _ingested_at DESC;

-- DQ Results
SELECT * FROM CLAIMS_DEMO.OPS.DQ_RESULTS ORDER BY run_ts DESC;

-- Pipe status
SELECT SYSTEM$PIPE_STATUS('CLAIMS_DEMO.OPS.PIPE_CLAIMS_AUTO');

-- Task history (last 2 hours)
SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
  SCHEDULED_TIME_RANGE_START=>DATEADD('HOUR', -2, CURRENT_TIMESTAMP()),
  SCHEDULED_TIME_RANGE_END=>CURRENT_TIMESTAMP()
))
WHERE NAME ILIKE '%TASK_MERGE_CLAIMS%'
ORDER BY SCHEDULED_TIME DESC;